[versions]
minecraft = "1.21.11"
yarn = "1.21.11+build.5"
fabric_loader = "0.19.2"
fabric_api = "0.141.3+1.21.11"
midnightlib = "1.9.2+1.21.11-fabric"
modmenu = "17.0.0"

fabric_loom = "1.16-SNAPSHOT"
publishing = "0.6.2"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
yarn = { module = "net.fabricmc:yarn", version.ref = "yarn" }

fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric_loader" }
fabric_api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric_api" }
midnightlib = { module = "maven.modrinth:midnightlib", version.ref = "midnightlib" }
modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu" }
# If you have multiple similar dependencies, you can declare a dependency bundle and reference it on the build script with "libs.bundles.example".
[bundles]

[plugins]
#     id "me.modmuss50.mod-publish-plugin" version "0.3.5"
fabric_loom = { id = "fabric-loom", version.ref = "fabric_loom" }
publishing = { id = "me.modmuss50.mod-publish-plugin", version.ref = "publishing" }
